name: Build Engine Action
on:
  pull_request:
    types:
      - opened
  pull_request_review:
    types: 
      - submitted
jobs:
  Build-Windows:
    uses: ./.github/workflows/build.yml
    with:
      runs_on: 'windows-latest'
  Build-Linux:
    uses: ./.github/workflows/build.yml
    with:
      runs_on: 'ubuntu-latest'
  Build-MacOS:
    uses: ./.github/workflows/build.yml
    with:
      runs_on: 'macos-latest'
